# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  romarinhoapi:
    image: romarinhoapi
    build:
      context: .
      dockerfile: Romarinho.Api/Dockerfile
    ports:
      - 5001:5001
  romarinhosocket:
    image: romarinhosocket
    build:
      context: .
      dockerfile: Romarinho.Socket/Dockerfile
    ports:
      - 5002:5002
#  database:
#    image: romarinho-db
#    build:
#      context: .
#      dockerfile: dockerfiledb
#    ports:
#        - "3306:3306"
#    environment:
#        mysql_root_password: romarinho
#        mysql_database: romarinho
#        mysql_user: mainuser
#        mysql_password: mainpassword